### ISSUE TITLE
ConnectionRefusedError

### ISSUE THREAD

**Issue by Charlotte-Yiyao-CHEN** [paperswithcode/axcell#12]
Hi,

When I tried to run this line in the evaluation notebook,

results = Parallel(backend='multiprocessing', n_jobs=-1)(delayed(process_single)(index) for index in range(len(pc)))

I encountered the following error:

07/03/2020 13:32:37 - WARNING - elasticsearch - PUT http://127.0.0.1:9200/paper-fragments/_doc/1207.4708v2_1000 [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/opt/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/opt/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

Do you have any idea to resolve this issue?

**Comment by mkardas** [comment]
Hi,

we use an ElasticSearch instance to index and retrieve papers. You can start it using `docker-compose up -d` in the main directory of the repository. The information was present only in the results-extraction notebook, so I've put it to the evaluation notebook as well.
